// <auto-generated />
using System;
using Clinicks.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinicks.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClinicksDbContext))]
    partial class ClinicksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinicks.Domain.Entities.Cama", b =>
                {
                    b.Property<int>("NCama")
                        .HasColumnType("int")
                        .HasColumnName("n_cama");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int")
                        .HasColumnName("id_habitacion");

                    b.Property<string>("Ocupado")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ocupado");

                    b.HasKey("NCama", "IdHabitacion")
                        .HasName("PK__Cama");

                    b.HasIndex("IdHabitacion");

                    b.ToTable("Cama", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Ciudad", b =>
                {
                    b.Property<int>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ciudad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCiudad"));

                    b.Property<int?>("IdProvincia")
                        .HasColumnType("int")
                        .HasColumnName("id_provincia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCiudad")
                        .HasName("PK__Ciudad");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Ciudad", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_direccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccion"));

                    b.Property<int>("Altura")
                        .HasColumnType("int")
                        .HasColumnName("altura");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("calle");

                    b.Property<int?>("Dni")
                        .HasColumnType("int")
                        .HasColumnName("dni");

                    b.Property<int?>("IdCiudad")
                        .HasColumnType("int")
                        .HasColumnName("id_ciudad");

                    b.HasKey("IdDireccion")
                        .HasName("PK__Direccion");

                    b.HasIndex("Dni");

                    b.HasIndex("IdCiudad");

                    b.ToTable("Direccion", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Egreso", b =>
                {
                    b.Property<int>("IdEgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_egreso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEgreso"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdInternacion")
                        .HasColumnType("int")
                        .HasColumnName("id_internacion");

                    b.HasKey("IdEgreso")
                        .HasName("PK__Egreso");

                    b.HasIndex("IdInternacion");

                    b.ToTable("Egreso", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Habitacion", b =>
                {
                    b.Property<int>("IdHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_habitacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitacion"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdHabitacion")
                        .HasName("PK__Habitacion");

                    b.ToTable("Habitacion", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Ingreso", b =>
                {
                    b.Property<int>("IdIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ingreso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIngreso"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdInternacion")
                        .HasColumnType("int")
                        .HasColumnName("id_internacion");

                    b.HasKey("IdIngreso")
                        .HasName("PK__Ingreso");

                    b.HasIndex("IdInternacion");

                    b.ToTable("Ingreso", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Internacion", b =>
                {
                    b.Property<int>("IdInternacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_internacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInternacion"));

                    b.Property<int?>("Dni")
                        .HasColumnType("int")
                        .HasColumnName("dni");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("IdHabitacion")
                        .HasColumnType("int")
                        .HasColumnName("id_habitacion");

                    b.Property<int?>("NCama")
                        .HasColumnType("int")
                        .HasColumnName("n_cama");

                    b.HasKey("IdInternacion")
                        .HasName("PK__Internacion");

                    b.HasIndex("Dni");

                    b.HasIndex("NCama", "IdHabitacion");

                    b.ToTable("Internacion", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Dni")
                        .HasColumnType("int")
                        .HasColumnName("dni");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Dni")
                        .HasName("PK__Paciente__D87608A6A9A48A2E");

                    b.ToTable("Paciente", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPais"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPais")
                        .HasName("PK__Pais");

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_provincia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProvincia"));

                    b.Property<int?>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdProvincia")
                        .HasName("PK__Provincia");

                    b.HasIndex("IdPais");

                    b.ToTable("Provincia", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Traslado", b =>
                {
                    b.Property<int>("IdTraslado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_traslado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTraslado"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdInternacionDestino")
                        .HasColumnType("int")
                        .HasColumnName("id_internacion_destino");

                    b.Property<int?>("IdInternacionOrigen")
                        .HasColumnType("int")
                        .HasColumnName("id_internacion_origen");

                    b.HasKey("IdTraslado")
                        .HasName("PK__Traslado");

                    b.HasIndex("IdInternacionDestino");

                    b.HasIndex("IdInternacionOrigen");

                    b.ToTable("Traslado", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<int>("Rol")
                        .HasColumnType("int")
                        .HasColumnName("rol");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuario__2ED7D2AF6D9861A0");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuario__AB6E6164028903F3")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Cama", b =>
                {
                    b.HasOne("Clinicks.Domain.Entities.Habitacion", "HabitacionNavigation")
                        .WithMany("Camas")
                        .HasForeignKey("IdHabitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Cama__id_habitac");

                    b.Navigation("HabitacionNavigation");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Ciudad", b =>
                {
                    b.HasOne("Clinicks.Domain.Entities.Provincia", "ProvinciaNavigation")
                        .WithMany("Ciudades")
                        .HasForeignKey("IdProvincia")
                        .HasConstraintName("FK__Ciudad__id_provi");

                    b.Navigation("ProvinciaNavigation");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Direccion", b =>
                {
                    b.HasOne("Clinicks.Domain.Entities.Paciente", "PacienteNavigation")
                        .WithMany("Direcciones")
                        .HasForeignKey("Dni")
                        .HasConstraintName("FK_Direccion_Paciente");

                    b.HasOne("Clinicks.Domain.Entities.Ciudad", "CiudadNavigation")
                        .WithMany("Direcciones")
                        .HasForeignKey("IdCiudad")
                        .HasConstraintName("FK__Direccion__id_ci");

                    b.Navigation("CiudadNavigation");

                    b.Navigation("PacienteNavigation");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Egreso", b =>
                {
                    b.HasOne("Clinicks.Domain.Entities.Internacion", "InternacionNavigation")
                        .WithMany("Egresos")
                        .HasForeignKey("IdInternacion")
                        .HasConstraintName("FK__Egreso__id_inter");

                    b.Navigation("InternacionNavigation");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Ingreso", b =>
                {
                    b.HasOne("Clinicks.Domain.Entities.Internacion", "InternacionNavigation")
                        .WithMany("Ingresos")
                        .HasForeignKey("IdInternacion")
                        .HasConstraintName("FK__Ingreso__id_inte");

                    b.Navigation("InternacionNavigation");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Internacion", b =>
                {
                    b.HasOne("Clinicks.Domain.Entities.Paciente", "PacienteNavigation")
                        .WithMany("Internaciones")
                        .HasForeignKey("Dni")
                        .HasConstraintName("FK__Internacion__dni");

                    b.HasOne("Clinicks.Domain.Entities.Cama", "CamaNavigation")
                        .WithMany("Internaciones")
                        .HasForeignKey("NCama", "IdHabitacion")
                        .HasConstraintName("FK__Internacion__cama");

                    b.Navigation("CamaNavigation");

                    b.Navigation("PacienteNavigation");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Provincia", b =>
                {
                    b.HasOne("Clinicks.Domain.Entities.Pais", "PaisNavigation")
                        .WithMany("Provincias")
                        .HasForeignKey("IdPais")
                        .HasConstraintName("FK__Provincia__id_pa");

                    b.Navigation("PaisNavigation");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Traslado", b =>
                {
                    b.HasOne("Clinicks.Domain.Entities.Internacion", "InternacionDestinoNavigation")
                        .WithMany("TrasladosDestino")
                        .HasForeignKey("IdInternacionDestino")
                        .HasConstraintName("FK__Traslado__destin");

                    b.HasOne("Clinicks.Domain.Entities.Internacion", "InternacionOrigenNavigation")
                        .WithMany("TrasladosOrigen")
                        .HasForeignKey("IdInternacionOrigen")
                        .HasConstraintName("FK__Traslado__origen");

                    b.Navigation("InternacionDestinoNavigation");

                    b.Navigation("InternacionOrigenNavigation");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Cama", b =>
                {
                    b.Navigation("Internaciones");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Ciudad", b =>
                {
                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Habitacion", b =>
                {
                    b.Navigation("Camas");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Internacion", b =>
                {
                    b.Navigation("Egresos");

                    b.Navigation("Ingresos");

                    b.Navigation("TrasladosDestino");

                    b.Navigation("TrasladosOrigen");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Internaciones");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Pais", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("Clinicks.Domain.Entities.Provincia", b =>
                {
                    b.Navigation("Ciudades");
                });
#pragma warning restore 612, 618
        }
    }
}
